apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubepiter-cluster-roles
  namespace: kubepiter
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - apps
      - rbac.authorization.k8s.io
      - metrics.k8s.io
      - networking.k8s.io
    resources:
      - nodes
      - pods
      - pods/log
      - ingresses
      - deployments
      - services
      - secrets
